apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: helm-demo-pipeline
  labels:
    app: helm-demo
description: helm-demo delivery pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles:
    - dev
  - targetId: prod
    profiles:
    - prod
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/PROJECT_ID/locations/REGION/clusters/helm-demo-dev
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/PROJECT_ID/locations/REGION/clusters/helm-demo-prd
