apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: helm-cicd-pipeline
  labels:
    app: helm-cicd
description: helm-cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles:
    - dev
  - targetId: staging
    profiles:
    - staging
  - targetId: prod
    profiles:
    - prod
---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: helm-cicd-pipeline
  labels:
    app: helm-cicd
description: helm-cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles:
    - dev
  - targetId: staging
    profiles:
    - staging
  - targetId: prod
    profiles:
    - prod
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/kiwonlee-default/locations/us-central1/clusters/helm-cd-testing-prd